#!/bin/bash -eu

#
# Small script to view .pacnew diff through delta filter (from the git-delta package)
# Unfortunately 'DIFFPROG=delta pacdiff' does not work as intended in non interactive context
#

#
# To configure delta output, edit /root/.config/git/config
# See https://github.com/dandavison/delta#usage
#

for pacnew_path in $(pacdiff -o)
do
    modified_path="${pacnew_path%.pacnew}"
    if [ ! -r "${modified_path}" ] || [ "${pacnew_path}" = "${modified_path}" ]
    then
        continue
    fi
    diff -u "${pacnew_path}" "${modified_path}" | delta
done
